---
- hosts: Application
  become: true
  vars:
   - tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.75/bin/apache-tomcat-8.5.75.tar.gz
   - tomcat_package: apache-tomcat-8.5.75.tar.gz
  tasks:
  - name: Install java
    yum: 
      name: java
      state: present
  - name: Download the tomcat
    get_url:
      url: "{{ tomcat_url }}"
      dest: /opt
  - name: untar the file
    unarchive:
      src: /opt/{{ tomcat_package }}
      dest: /opt
      remote_src: True
  - name: Rename the tomcat
    command: mv /opt/{{ tomcat_package}} /opt/tomcat
  - name: start the tomcat
    shell: nohup /opt/tomcat/bin/startup.sh  
